name: test_ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check_code
        uses: actions/checkout@v2

      - name: Up Python
        uses:
        with:
          python-version: '3.8'
      
      - name: Install*
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      
      - name: Run tests
        run: |
          pytest

